/*
=================================================
================== Code generated by ai =========
=================================================
*/

#include "generator.hpp"
#include "pcg_random.hpp"

#include <map>
#include <set>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <chrono>

static pcg32 rng;

static int rnd(int a, int b)
{
    return a + rng.bounded(b - a + 1);
}

static bool chance(double p)
{
    return (double)rng() / UINT32_MAX < p;
}

static std::string now_iso()
{
    auto t = std::chrono::system_clock::to_time_t(
        std::chrono::system_clock::now());
    char buf[32];
    std::strftime(buf, sizeof(buf), "%FT%T", std::localtime(&t));
    return buf;
}


static const std::map<std::string, std::string> BLOBS = {
    {"gosuslugi", "@/opt/zapret2/files/fake/tls_clienthello_gosuslugi_ru.bin"},
    {"vk", "@/opt/zapret2/files/fake/tls_clienthello_vk_com.bin"},
    {"vk_kyber", "@/opt/zapret2/files/fake/tls_clienthello_vk_com_kyber.bin"},
    {"google", "@/opt/zapret2/files/fake/tls_clienthello_google_com_tlsrec.bin"}};

static const std::map<std::string, std::string> DOMAINS = {
    {"youtube", "youtube.com,www.youtube.com,googlevideo.com,gvt1.com,ytimg.com"},
    {"discord", "discord.com,discordapp.com,discord.gg,cdn.discordapp.com"}};

static const std::vector<std::string> SNIS = {
    "epp.genproc.gov.ru", "duma.gov.ru",
    "alfabank.ru", "pochta.ru",
    "moskva.taximaxim.ru",
    "2gis.ru",
    "tutu.ru",
    "rzd.ru",
    "rambler.ru",
    "lenta.ru",
    "gazeta.ru",
    "rbc.ru",
    "kp.ru",
    "government.ru",
    "kremlin.ru",
    "sun6-22.userapi.com",
    "pptest.userapi.com",
    "sun9-101.userapi.com",
    "travel.yandex.ru",
    "trk.mail.ru",
    "1l-api.mail.ru",
    "m.47news.ru",
    "crowdtest.payment-widget-smarttv.plus.tst.kinopoisk.ru",
    "external-api.mediabilling.kinopoisk.ru",
    "external-api.plus.kinopoisk.ru",
    "graphql-web.kinopoisk.ru",
    "graphql.kinopoisk.ru",
    "1l.mail.ru",
    "tickets.widget.kinopoisk.ru",
    "st.kinopoisk.ru",
    "quiz.kinopoisk.ru",
    "payment-widget.kinopoisk.ru",
    "payment-widget-smarttv.plus.kinopoisk.ru",
    "oneclick-payment.kinopoisk.ru",
    "microapps.kinopoisk.ru",
    "ma.kinopoisk.ru",
    "hd.kinopoisk.ru",
    "crowdtest.payment-widget.plus.tst.kinopoisk.ru",
    "api.plus.kinopoisk.ru",
    "st-im.kinopoisk.ru",
    "1l-s2s.mail.ru",
    "sso.kinopoisk.ru",
    "touch.kinopoisk.ru",
    "1l-view.mail.ru",
    "1link.mail.ru",
    "1l-hit.mail.ru",
    "2021.mail.ru",
    "2018.mail.ru",
    "23feb.mail.ru",
    "2019.mail.ru",
    "2020.mail.ru",
    "1l-go.mail.ru",
    "8mar.mail.ru",
    "9may.mail.ru",
    "aa.mail.ru",
    "8march.mail.ru",
    "afisha.mail.ru",
    "agent.mail.ru",
    "amigo.mail.ru",
    "analytics.predict.mail.ru",
    "alpha4.minigames.mail.ru",
    "alpha3.minigames.mail.ru",
    "answer.mail.ru",
    "api.predict.mail.ru",
    "answers.mail.ru",
    "authdl.mail.ru",
    "av.mail.ru",
    "apps.research.mail.ru",
    "auto.mail.ru",
    "bb.mail.ru",
    "bender.mail.ru",
    "beko.dom.mail.ru",
    "azt.mail.ru",
    "bd.mail.ru",
    "autodiscover.corp.mail.ru",
    "aw.mail.ru",
    "beta.mail.ru",
    "biz.mail.ru",
    "blackfriday.mail.ru",
    "bitva.mail.ru",
    "blog.mail.ru",
    "bratva-mr.mail.ru",
    "browser.mail.ru",
    "calendar.mail.ru",
    "capsula.mail.ru",
    "cloud.mail.ru",
    "cdn.newyear.mail.ru",
    "cars.mail.ru",
    "code.mail.ru",
    "cobmo.mail.ru",
    "cobma.mail.ru",
    "cog.mail.ru",
    "cdn.connect.mail.ru",
    "cf.mail.ru",
    "comba.mail.ru",
    "compute.mail.ru",
    "codefest.mail.ru",
    "combu.mail.ru",
    "corp.mail.ru",
    "commba.mail.ru",
    "crazypanda.mail.ru",
    "ctlog.mail.ru",
    "cpg.money.mail.ru",
    "ctlog2023.mail.ru",
    "ctlog2024.mail.ru",
    "cto.mail.ru",
    "cups.mail.ru",
    "da.biz.mail.ru",
    "da-preprod.biz.mail.ru",
    "data.amigo.mail.ru",
    "dk.mail.ru",
    "dev1.mail.ru",
    "dev3.mail.ru",
    "dl.mail.ru",
    "deti.mail.ru",
    "dn.mail.ru",
    "dl.marusia.mail.ru",
    "doc.mail.ru",
    "dragonpals.mail.ru",
    "dom.mail.ru",
    "duck.mail.ru",
    "dev2.mail.ru",
    "e.mail.ru",
    "ds.mail.ru",
    "education.mail.ru",
    "dobro.mail.ru",
    "esc.predict.mail.ru",
    "et.mail.ru",
    "fe.mail.ru",
    "finance.mail.ru",
    "five.predict.mail.ru",
    "foto.mail.ru",
    "games-bamboo.mail.ru",
    "games-fisheye.mail.ru",
    "games.mail.ru",
    "genesis.mail.ru",
    "geo-apart.predict.mail.ru",
    "golos.mail.ru",
    "go.mail.ru",
    "gpb.finance.mail.ru",
    "gibdd.mail.ru",
    "health.mail.ru",
    "guns.mail.ru",
    "horo.mail.ru",
    "hs.mail.ru",
    "help.mcs.mail.ru",
    "imperia.mail.ru",
    "it.mail.ru",
    "internet.mail.ru",
    "infra.mail.ru",
    "hi-tech.mail.ru",
    "jd.mail.ru",
    "journey.mail.ru",
    "junior.mail.ru",
    "juggermobile.mail.ru",
    "kicker.mail.ru",
    "knights.mail.ru",
    "kino.mail.ru",
    "kingdomrift.mail.ru",
    "kobmo.mail.ru",
    "komba.mail.ru",
    "kobma.mail.ru",
    "kommba.mail.ru",
    "kombo.mail.ru",
    "kz.mcs.mail.ru",
    "konflikt.mail.ru",
    "kombu.mail.ru",
    "lady.mail.ru",
    "landing.mail.ru",
    "la.mail.ru",
    "legendofheroes.mail.ru",
    "legenda.mail.ru",
    "loa.mail.ru",
    "love.mail.ru",
    "lotro.mail.ru",
    "mailer.mail.ru",
    "mailexpress.mail.ru",
    "man.mail.ru",
    "maps.mail.ru",
    "marusia.mail.ru",
    "mcs.mail.ru",
    "media-golos.mail.ru",
    "mediapro.mail.ru",
    "merch-cpg.money.mail.ru",
    "miniapp.internal.myteam.mail.ru",
    "media.mail.ru",
    "mobfarm.mail.ru",
    "mowar.mail.ru",
    "mozilla.mail.ru",
    "my.mail.ru",
    "mosqa.mail.ru",
    "mking.mail.ru",
    "minigames.mail.ru",
    "myteam.mail.ru",
    "nebogame.mail.ru",
    "money.mail.ru",
    "net.mail.ru",
    "new.mail.ru",
    "newyear2018.mail.ru",
    "news.mail.ru",
    "newyear.mail.ru",
    "nonstandard.sales.mail.ru",
    "notes.mail.ru",
    "octavius.mail.ru",
    "operator.mail.ru",
    "otvety.mail.ru",
    "otvet.mail.ru",
    "otveti.mail.ru",
    "panzar.mail.ru",
    "park.mail.ru",
    "pernatsk.mail.ru",
    "pay.mail.ru",
    "pets.mail.ru",
    "pms.mail.ru",
    "pochtabank.mail.ru",
    "pokerist.mail.ru",
    "pogoda.mail.ru",
    "polis.mail.ru",
    "predict.mail.ru",
    "primeworld.mail.ru",
    "pp.mail.ru",
    "ptd.predict.mail.ru",
    "public.infra.mail.ru",
    "pulse.mail.ru",
    "pubg.mail.ru",
    "quantum.mail.ru",
    "rate.mail.ru",
    "pw.mail.ru",
    "rebus.calls.mail.ru",
    "rebus.octavius.mail.ru",
    "rev.mail.ru",
    "rl.mail.ru",
    "rm.mail.ru",
    "riot.mail.ru",
    "reseach.mail.ru",
    "s3.babel.mail.ru",
    "rt.api.operator.mail.ru",
    "s3.mail.ru",
    "s3.media-mobs.mail.ru",
    "sales.mail.ru",
    "sangels.mail.ru",
    "sdk.money.mail.ru",
    "service.amigo.mail.ru",
    "security.mail.ru",
    "shadowbound.mail.ru",
    "socdwar.mail.ru",
    "sochi-park.predict.mail.ru",
    "souz.mail.ru",
    "sphere.mail.ru",
    "staging-analytics.predict.mail.ru",
    "staging-sochi-park.predict.mail.ru",
    "staging-esc.predict.mail.ru",
    "stand.bb.mail.ru",
    "sport.mail.ru",
    "stand.aoc.mail.ru",
    "stand.cb.mail.ru",
    "startrek.mail.ru",
    "static.dl.mail.ru",
    "stand.pw.mail.ru",
    "stand.la.mail.ru",
    "stormriders.mail.ru",
    "static.operator.mail.ru",
    "stream.mail.ru",
    "status.mcs.mail.ru",
    "street-combats.mail.ru",
    "support.biz.mail.ru",
    "support.mcs.mail.ru",
    "team.mail.ru",
    "support.tech.mail.ru",
    "tech.mail.ru",
    "tera.mail.ru",
    "tiles.maps.mail.ru",
    "todo.mail.ru",
    "tidaltrek.mail.ru",
    "tmgame.mail.ru",
    "townwars.mail.ru",
    "tv.mail.ru",
    "ttbh.mail.ru",
    "typewriter.mail.ru",
    "u.corp.mail.ru",
    "ufo.mail.ru",
    "vkdoc.mail.ru",
    "vk.mail.ru",
    "voina.mail.ru",
    "warface.mail.ru",
    "wartune.mail.ru",
    "weblink.predict.mail.ru",
    "warheaven.mail.ru",
    "welcome.mail.ru",
    "webstore.mail.ru",
    "webagent.mail.ru",
    "wf.mail.ru",
    "whatsnew.mail.ru",
    "wh-cpg.money.mail.ru",
    "wok.mail.ru",
    "www.biz.mail.ru",
    "wos.mail.ru",
    "www.mail.ru",
    "www.pubg.mail.ru",
    "www.wf.mail.ru",
    "www.mcs.mail.ru",
    "informer.yandex.ru",
    "digital.gov.ru",
    "adm.digital.gov.ru",
    "travel.yastatic.net",
    "api.uxfeedback.yandex.net",
    "api.s3.yandex.net",
    "cdn.s3.yandex.net",
    "uxfeedback-cdn.s3.yandex.net",
    "uxfeedback.yandex.ru",
    "cloudcdn-m9-15.cdn.yandex.net",
    "cloudcdn-m9-14.cdn.yandex.net",
    "cloudcdn-m9-13.cdn.yandex.net",
    "cloudcdn-m9-12.cdn.yandex.net",
    "cloudcdn-m9-10.cdn.yandex.net",
    "cloudcdn-m9-9.cdn.yandex.net",
    "cloudcdn-m9-7.cdn.yandex.net",
    "cloudcdn-m9-6.cdn.yandex.net",
    "cloudcdn-m9-5.cdn.yandex.net",
    "cloudcdn-m9-4.cdn.yandex.net",
    "cloudcdn-m9-3.cdn.yandex.net",
    "cloudcdn-m9-2.cdn.yandex.net",
    "admin.cs7777.vk.ru",
    "admin.tau.vk.ru",
    "analytics.vk.ru",
    "api.cs7777.vk.ru",
    "owa.ozon.ru",
    "learning.ozon.ru",
    "mapi.learning.ozon.ru",
    "ws.seller.ozon.ru",
    "bank.ozon.ru",
    "www.cikrf.ru",
    "izbirkom.ru",
    "seller.ozon.ru",
    "pay.ozon.ru",
    "securepay.ozon.ru",
    "adv.ozon.ru",
    "voter.gosuslugi.ru",
    "gosweb.gosuslugi.ru",
    "invest.ozon.ru",
    "ord.ozon.ru",
    "autodiscover.ord.ozon.ru",
    "api.tau.vk.ru",
    "fw.wb.ru",
    "finance.wb.ru",
    "jitsi.wb.ru",
    "dnd.wb.ru",
    "live.ok.ru",
    "m.ok.ru",
    "api.ok.ru",
    "multitest.ok.ru",
    "dating.ok.ru",
    "tamtam.ok.ru",
    "away.cs7777.vk.ru",
    "away.tau.vk.ru",
    "business.vk.ru",
    "connect.cs7777.vk.ru",
    "cs7777.vk.ru",
    "dev.cs7777.vk.ru",
    "dev.tau.vk.ru",
    "expert.vk.ru",
    "id.cs7777.vk.ru",
    "id.tau.vk.ru",
    "login.cs7777.vk.ru",
    "login.tau.vk.ru",
    "m.cs7777.vk.ru",
    "m.tau.vk.ru",
    "m.vk.ru",
    "m.vkvideo.cs7777.vk.ru",
    "me.cs7777.vk.ru",
    "ms.cs7777.vk.ru",
    "music.vk.ru",
    "oauth.cs7777.vk.ru",
    "oauth.tau.vk.ru",
    "oauth2.cs7777.vk.ru",
    "ord.vk.ru",
    "push.vk.ru",
    "r.vk.ru",
    "target.vk.ru",
    "tech.vk.ru",
    "ui.cs7777.vk.ru",
    "ui.tau.vk.ru",
    "vkvideo.cs7777.vk.ru",
    "stats.vk-portal.net",
    "mediafeeds.yandex.ru",
    "cdn.tbank.ru",
    "uslugi.yandex.ru",
    "auto.ru",
    "http-check-headers.yandex.ru",
    "sso.auto.ru",
    "hrc.tbank.ru",
    "static.rutube.ru",
    "kiks.yandex.ru",
    "cobrowsing.tbank.ru",
    "sun6-20.userapi.com",
    "ssp.rutube.ru",
    "preview.rutube.ru",
    "st-ok.cdn-vk.ru",
    "ekmp-a-51.rzd.ru",
    "mp.rzd.ru",
    "pulse.mp.rzd.ru",
    "link.mp.rzd.ru",
    "adm.mp.rzd.ru",
    "welcome.rzd.ru",
    "travel.rzd.ru",
    "secure-cloud.rzd.ru",
    "secure.rzd.ru",
    "market.rzd.ru",
    "ticket.rzd.ru",
    "my.rzd.ru",
    "prodvizhenie.rzd.ru",
    "disk.rzd.ru",
    "rzd.ru",
    "www.rzd.ru",
    "team.rzd.ru",
    "contacts.rzd.ru",
    "cargo.rzd.ru",
    "company.rzd.ru",
    "avatars.mds.yandex.net",
    "mc.yandex.ru",
    "www.vtb.ru",
    "chat3.vtb.ru",
    "s.vtb.ru",
    "sso-app4.vtb.ru",
    "sso-app5.vtb.ru",
    "cdn.lemanapro.ru",
    "dmp.dmpkit.lemanapro.ru",
    "receive-sentry.lmru.tech",
    "partners.lemanapro.ru",
    "metrics.alfabank.ru",
    "static.lemanapro.ru",
    "lemanapro.ru",
    "frontend.vh.yandex.ru",
    "yandex.net",
    "favicon.yandex.ru",
    "favicon.yandex.com",
    "favicon.yandex.net",
    "gu-st.ru",
    "browser.yandex.com",
    "api.browser.yandex.com",
    "wap.yandex.com",
    "kiks.yandex.com",
    "rs.mail.ru",
    "yandex.com",
    "mediafeeds.yandex.com",
    "avatars.mds.yandex.com",
    "mc.yandex.com",
    "api-maps.yandex.ru",
    "enterprise.api-maps.yandex.ru",
    "dzen.ru",
    "300.ya.ru",
    "ya.ru",
    "brontp-pre.yandex.ru",
    "suggest.dzen.ru",
    "dr2.yandex.net",
    "cloud.cdn.yandex.net",
    "api.browser.yandex.ru",
    "wap.yandex.ru",
    "cloud.cdn.yandex.com",
    "dr.yandex.net",
    "mail.yandex.ru",
    "mail.yandex.com",
    "yabs.yandex.ru",
    "neuro.translate.yandex.ru",
    "cloud.cdn.yandex.ru",
    "ws-api.oneme.ru",
    "cdn.yandex.ru",
    "3475482542.mc.yandex.ru",
    "ads.vk.ru",
    "s3.yandex.net",
    "browser.yandex.ru",
    "vk-portal.net",
    "login.vk.ru",
    "pic.rutubelist.ru",
    "zen.yandex.ru",
    "zen.yandex.com",
    "zen.yandex.net",
    "le.tbank.ru",
    "rutube.ru",
    "queuev4.vk.com",
    "api.vk.ru",
    "collections.yandex.ru",
    "r0.mradx.net",
    "collections.yandex.com",
    "zen-yabro-morda.mediascope.mc.yandex.ru",
    "yandex.ru",
    "bro-bg-store.s3.yandex.ru",
    "bro-bg-store.s3.yandex.net",
    "bro-bg-store.s3.yandex.com",
    "www.sberbank.ru",
    "static-mon.yandex.net",
    "id.tbank.ru",
    "sync.browser.yandex.net",
    "storage.ape.yandex.net",
    "top-fwz1.mail.ru",
    "sberbank.ru",
    "cms-res-web.online.sberbank.ru",
    "sfd.gosuslugi.ru",
    "esia.gosuslugi.ru",
    "ams2-cdn.2gis.com",
    "bot.gosuslugi.ru",
    "gosuslugi.ru",
    "contract.gosuslugi.ru",
    "novorossiya.gosuslugi.ru",
    "pos.gosuslugi.ru",
    "lk.gosuslugi.ru",
    "map.gosuslugi.ru",
    "partners.gosuslugi.ru",
    "www.gosuslugi.ru",
    "eh.vk.com",
    "akashi.vk-portal.net"};


static void resolve_blob(
    const std::string &blob,
    std::string &blob_name,
    std::string &blob_path)
{
    if (blob.find('/') != std::string::npos)
    {
        blob_name = "custom";
        blob_path = blob;
        return;
    }

    if (BLOBS.count(blob))
    {
        blob_name = blob;
        blob_path = BLOBS.at(blob);
        return;
    }

    blob_name = "custom";
    blob_path = blob;
}



FastStrategyGenerator::FastStrategyGenerator() {}

std::vector<std::string>
FastStrategyGenerator::gen_simple(
    const std::string& service,
    const std::string& blob_name,
    const std::string& blob_path,
    int count)
{
    std::set<std::string> out;

    std::string dom =
        DOMAINS.count(service) ? DOMAINS.at(service)
                                : DOMAINS.begin()->second;

    while ((int)out.size() < count)
    {
        std::stringstream s;
        s << "--blob=fake_" << blob_name << ":" << blob_path
            << " --filter-tcp=443 --filter-l7=tls "
            << "--hostlist-domains=" << dom
            << " --out-range=-d10 --payload=tls_client_hello "
            << "--lua-desync=fake:blob=fake_" << blob_name
            << ":tcp_ts=" << rnd(-15000, -3000)
            << ":repeats=" << rnd(2, 10);

        if (chance(0.4)) s << ":tls_mod=rnd";
        if (chance(0.3)) s << ":ip_ttl=" << rnd(2, 5);

        if (chance(0.3))
            s << " --lua-desync=multisplit:pos="
                << rnd(5, 30) << ":seqovl=" << rnd(600, 800);

        out.insert(s.str());
    }

    return {out.begin(), out.end()};
}

std::vector<std::string>
FastStrategyGenerator::gen_advanced(
    const std::string& service,
    const std::string& blob_name,
    const std::string& blob_path,
    int count,
    int complexity)
{
    std::set<std::string> out;

    std::string dom =
        DOMAINS.count(service) ? DOMAINS.at(service)
                                : DOMAINS.begin()->second;

    int tries = 0;

    while ((int)out.size() < count && tries < count * 10)
    {
        std::stringstream fake;
        fake << "tcp_ts=" << rnd(-80000, -20000)
                << ":repeats=" << rnd(20, 300);

        if (chance(0.5)) fake << ":ip_ttl=" << rnd(2, 5);
        if (chance(0.5)) fake << ":tcp_ack=" << rnd(6000, 30000);
        if (chance(0.4))
            fake << ":tls_mod=sni=" << SNIS[rnd(0, SNIS.size() - 1)];

        std::stringstream s;
        s << "--blob=fake_" << blob_name << ":" << blob_path
            << " --filter-tcp=443 --filter-l7=tls "
            << "--hostlist-domains=" << dom
            << " --out-range=-d10 --payload=tls_client_hello "
            << "--lua-desync=fake:blob=fake_" << blob_name
            << ":" << fake.str();

        if (chance(0.5))
            s << " --lua-desync=multidisorder:pos="
                << rnd(30, 150) << ":seqovl=" << rnd(600, 2000);

        out.insert(s.str());
        ++tries;
    }

    return {out.begin(), out.end()};
}

std::vector<std::string>
FastStrategyGenerator::gen_mixed(
    const std::string& service,
    const std::string& blob_name,
    const std::string& blob_path,
    int count)
{
    auto a = gen_simple(service, blob_name, blob_path, count / 2);
    auto d = gen_advanced(service, blob_name, blob_path,
                            count - (int)a.size(), 3);
    a.insert(a.end(), d.begin(), d.end());
    return a;
}


void FastStrategyGenerator::save_txt(
    const std::vector<std::string> &v,
    const std::string &f)
{
    std::ofstream o(f);
    o << "# zapret2 strategies\n# Total: " << v.size() << "\n\n";
    int i = 1;
    for (auto &s : v)
    {
        o << "# Strategy #" << std::setw(4) << std::setfill('0') << i++ << "\n";
        o << "NFQWS2_OPT=\"" << s << "\"\n\n";
    }
}

void FastStrategyGenerator::save_json(
    const std::vector<std::string> &v,
    const std::string &f)
{
    std::ofstream o(f);
    o << "{\n  \"count\": " << v.size()
    << ",\n  \"generated_at\": \"" << now_iso()
    << "\",\n  \"strategies\": [\n";
    for (size_t i = 0; i < v.size(); ++i)
    {
        o << "    \"" << v[i] << "\""
        << (i + 1 < v.size() ? "," : "") << "\n";
    }
    o << "  ]\n}\n";
}
