/*
=================================================
================== Code generated by ai =========
=================================================
*/

#include "generator.hpp"
#include "pcg_random.hpp"

#include <map>
#include <set>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <chrono>

static pcg32 rng;

static int rnd(int a, int b) {
    return a + rng.bounded(b - a + 1);
}

static bool chance(double p) {
    return (double)rng() / UINT32_MAX < p;
}

static std::string now_iso() {
    auto t = std::chrono::system_clock::to_time_t(
        std::chrono::system_clock::now());
    char buf[32];
    std::strftime(buf, sizeof(buf), "%FT%T", std::localtime(&t));
    return buf;
}

/* --- tables --- */

static const std::map<std::string,std::string> BLOBS = {
    {"gosuslugi","@/opt/zapret2/files/fake/tls_clienthello_gosuslugi_ru.bin"},
    {"vk","@/opt/zapret2/files/fake/tls_clienthello_vk_com.bin"},
    {"vk_kyber","@/opt/zapret2/files/fake/tls_clienthello_vk_com_kyber.bin"},
    {"google","@/opt/zapret2/files/fake/tls_clienthello_google_com_tlsrec.bin"}
};

static const std::map<std::string,std::string> DOMAINS = {
    {"youtube","youtube.com,www.youtube.com,googlevideo.com,gvt1.com,ytimg.com"},
    {"discord","discord.com,discordapp.com,discord.gg,cdn.discordapp.com"}
};

static const std::vector<std::string> SNIS = {
    "www.google.com","googlevideo.com","ytimg.com",
    "cloudflare.com","discord.com"
};

/* --- ctor --- */
FastStrategyGenerator::FastStrategyGenerator() {}

/* --- simple --- */
std::vector<std::string>
FastStrategyGenerator::gen_simple(
    const std::string& service,
    const std::string& blob,
    int count)
{
    std::set<std::string> out;
    std::string dom =
        DOMAINS.count(service) ? DOMAINS.at(service) : DOMAINS.begin()->second;
    std::string blobp =
        BLOBS.count(blob) ? BLOBS.at(blob) : BLOBS.begin()->second;

    while ((int)out.size() < count) {
        std::stringstream s;
        s << "--blob=fake_" << blob << ":" << blobp
            << " --filter-tcp=443 --filter-l7=tls "
            << "--hostlist-domains=" << dom
            << " --out-range=-d10 --payload=tls_client_hello "
            << "--lua-desync=fake:blob=fake_" << blob
            << ":tcp_ts=" << rnd(-15000,-3000)
            << ":repeats=" << rnd(2,5);

        if (chance(0.4)) s << ":tls_mod=rnd";
        if (chance(0.3)) s << ":ip_ttl=" << rnd(2,5);

        if (chance(0.3))
            s << " --lua-desync=multisplit:pos="
                << rnd(5,30) << ":seqovl=" << rnd(600,800);

        out.insert(s.str());
    }

    return {out.begin(), out.end()};
}

/* --- advanced --- */
std::vector<std::string>
FastStrategyGenerator::gen_advanced(
    const std::string& service,
    const std::string& blob,
    int count,
    int complexity)
{
    std::set<std::string> out;
    std::string dom =
        DOMAINS.count(service) ? DOMAINS.at(service) : DOMAINS.begin()->second;
    std::string blobp =
        BLOBS.count(blob) ? BLOBS.at(blob) : BLOBS.begin()->second;

    int tries = 0;

    while ((int)out.size() < count && tries < count * 10) {
        std::stringstream fake;
        fake << "tcp_ts=" << rnd(-80000,-20000)
                << ":repeats=" << rnd(20,300);

        if (chance(0.5)) fake << ":ip_ttl=" << rnd(2,5);
        if (chance(0.5)) fake << ":tcp_ack=" << rnd(6000,30000);

        if (chance(0.4))
            fake << ":tls_mod=sni=" << SNIS[rnd(0,SNIS.size()-1)];

        std::stringstream s;
        s << "--blob=fake_" << blob << ":" << blobp
            << " --filter-tcp=443 --filter-l7=tls "
            << "--hostlist-domains=" << dom
            << " --out-range=-d10 --payload=tls_client_hello "
            << "--lua-desync=fake:blob=fake_" << blob
            << ":" << fake.str();

        if (chance(0.5))
            s << " --lua-desync=multidisorder:pos="
                << rnd(30,150) << ":seqovl=" << rnd(600,2000);

        if (complexity == 3 && chance(0.3))
            s << " --lua-desync=ipfrag:frag_size="
                << rnd(64,160)
                << ":frag_count=" << rnd(10,30)
                << ":frag_delay=" << rnd(100,1000);

        out.insert(s.str());
        ++tries;
    }

    return {out.begin(), out.end()};
}

/* --- mixed --- */
std::vector<std::string>
FastStrategyGenerator::gen_mixed(
    const std::string& s,
    const std::string& b,
    int c)
{
    auto a = gen_simple(s,b,c/2);
    auto d = gen_advanced(s,b,c-(int)a.size(),3);
    a.insert(a.end(), d.begin(), d.end());
    return a;
}

/* --- save --- */
void FastStrategyGenerator::save_txt(
    const std::vector<std::string>& v,
    const std::string& f)
{
    std::ofstream o(f);
    o << "# zapret2 strategies\n# Total: " << v.size() << "\n\n";
    int i = 1;
    for (auto& s : v) {
        o << "# Strategy #" << std::setw(4) << std::setfill('0') << i++ << "\n";
        o << "NFQWS2_OPT=\"" << s << "\"\n\n";
    }
}

void FastStrategyGenerator::save_json(
    const std::vector<std::string>& v,
    const std::string& f)
{
    std::ofstream o(f);
    o << "{\n  \"count\": " << v.size()
        << ",\n  \"generated_at\": \"" << now_iso()
        << "\",\n  \"strategies\": [\n";
    for (size_t i=0;i<v.size();++i) {
        o << "    \"" << v[i] << "\""
            << (i+1<v.size()? ",":"") << "\n";
    }
    o << "  ]\n}\n";
}
