/*
=================================================
================== Code generated by ai =========
=================================================
*/

#include "generator.hpp"
#include <iostream>
#include <sstream>
#include <filesystem>

static const char* HELP_TEXT = R"(zapret2-strategy-generator

Usage:
    nfqws2-strategy-gen --profiles | -p <list> [--count N] [--format txt|json]
    nfqws2-strategy-gen --help | -h

Required:
    --profiles <list>
        Comma-separated profiles in format:
        service:blob:mode[,service:blob:mode...]

Profile fields:
    service  Target service / domain group
            youtube | discord | instagram | twitter | reddit | pinterest
            (unknown -> youtube)

    blob     Fake TLS ClientHello preset
            gosuslugi | vk | vk_kyber | rutracker | max
            sberbank | google | iana | iana_big | random
            (unknown -> gosuslugi)

    mode     Strategy generation mode
            simple    - lightweight / fast
            advanced  - aggressive DPI bypass
            mixed     - simple + advanced (default)

Optional:
    --count | -c N
        Number of strategies per profile (default: 50)

    --format | -f txt|json
        Output format (default: txt)

Examples:
    nfqws2-strategy-gen --profiles youtube:gosuslugi:mixed
    nfqws2-strategy-gen --profiles youtube:gosuslugi:mixed,discord:vk:advanced
    nfqws2-strategy-gen --profiles youtube:random:mixed --count 100
)";


int main(int argc, char** argv) {
    std::string profiles, format = "txt";
    int count = 50;

    for (int i=1;i<argc;i++) {
        std::string a = argv[i];
        if (a=="--help" || a=="-h") {
            std::cout << HELP_TEXT;
            return 0;
        }
        else if (a=="--profiles" || a=="-p") profiles = argv[++i];
        else if (a=="--count" || a=="-c") count = std::stoi(argv[++i]);
        else if (a=="--format" || a=="-f") format = argv[++i];
    }

    if (profiles.empty()) {
        std::cerr << "Error: --profiles is required\n\n";
        std::cerr << HELP_TEXT;
        return 1;
    }


    FastStrategyGenerator gen;
    std::stringstream ss(profiles);
    std::string p;

    while (getline(ss,p,',')) {
        auto a = p.find(':'), b = p.rfind(':');
        auto service = p.substr(0,a);
        auto blob = p.substr(a+1,b-a-1);
        auto mode = p.substr(b+1);

        auto v =
            mode=="simple" ? gen.gen_simple(service,blob,count) :
            mode=="advanced" ? gen.gen_advanced(service,blob,count,3) :
            gen.gen_mixed(service,blob,count);

        std::string file = "strategies_"+service+"_"+blob+"_"+mode+"."+format;
        format=="json" ? gen.save_json(v,file) : gen.save_txt(v,file);

        std::cout << "✅ " << p << " → "
                    << std::filesystem::absolute(file) << "\n";
    }
}
