/*
=================================================
================== Code generated by ai =========
=================================================
*/

#pragma once
#include <cstdint>

struct pcg32 {
    uint64_t state = 0x853c49e6748fea9bULL;
    uint64_t inc   = 0xda3e39cb94b95bdbULL;

    uint32_t operator()() {
        uint64_t oldstate = state;
        state = oldstate * 6364136223846793005ULL + (inc | 1);
        uint32_t xorshifted = ((oldstate >> 18u) ^ oldstate) >> 27u;
        uint32_t rot = oldstate >> 59u;
        return (xorshifted >> rot) | (xorshifted << ((-rot) & 31));
    }

    uint32_t bounded(uint32_t bound) {
        uint32_t threshold = -bound % bound;
        while (true) {
            uint32_t r = (*this)();
            if (r >= threshold)
                return r % bound;
        }
    }
};